### ISSUE TITLE
Received unknown synced data key

### ISSUE THREAD

**Issue by denispionicul** [MrCrayfish/Obfuscate#35]
When trying to join a 1.16.5 server It gives me this error 
"Received unknown synced data key"
It's not the server either because there are players on it

**Comment by Shark-vil** [comment]
A similar problem. Just a few hours ago, everything worked fine.

**Fixed:**
I have not removed the addons from the server that were using this library. This caused a conflict on the client.

**Comment by denispionicul** [comment]
> A similar problem. Just a few hours ago, everything worked fine.
> 
> **Fixed:**
> I have not removed the addons from the server that were using this library. This caused a conflict on the client.

I haven't touched the server files either
I've waited 3 days. It still didn't fix, but thank you for your help

**Comment by MrCrayfish** [comment]
Going to close. Make sure you have the same mods as the server.
